# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe930a284dccdbb2d937c935536d847d8e8dea0aa9b85d756b2f69693b1965ea75bbb8289fcdbf0bb477fae4109f8189713d4834ca3ab1b0b4801980f94ebbab

test:
  secret_key_base: e4eac99fb4084fa14d923b54411716efcdef1eec1775b9c41bef80a676e5aa1be6bfad43a11c7a4de541309c07c154c66b890fbf17a660757edd18c2d9aa3bfd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
